name: myblog_proto_dart
version: 0.0.1
description: Compiled Protocol Buffers from myblog-proto for Dart language
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies: 
  protobuf: ^1.0.1
  grpc: ^2.1.3