name: myblog_proto_dart
version: 0.0.1
description: Compiled Protocol Buffers from myblog-proto for Dart language
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies: 
  protobuf: ^2.0.0
  grpc: ^3.0.0